name: binder

dependencies:
  - pip
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - blaze
  - bokeh
  - pip:
      - git+https://github.com/blaze/dask.git#egg=dask[complete]
      - git+https://github.com/blaze/castra.git#egg=castra
